apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
data:
  config.yaml: |
    # Models configured via config file
    # Add or modify models in the model_list below
    model_list:
      - model_name: nl-gpt-4.1
        litellm_params:
          model: gpt-4.1
          api_base: https://llm-proxy.edgez.live/v1
          api_key: sk-K2AyiqHTpNHDp3vhmpChjQ
      - model_name: nl-gpt-5
        litellm_params:
          model: gpt-5
          api_base: https://llm-proxy.edgez.live/v1
          api_key: sk-K2AyiqHTpNHDp3vhmpChjQ
